### ISSUE TITLE
iOS demo app gebruikt niet het ingevulde account id

### ISSUE THREAD

**Issue by Gerben-T** [parley-messaging/ios-library#1]
Zodra je de app voor het eerst installeert kan je een account id invullen, het maakt niet uit wat je daar invult want hij connect altijd met `0W4qcE5aXoKq9OzvHxj2`.

Zodra je je chat weg klikt en een nieuw account id invult probeert ie dit keer wel met het juiste account te verbinden alleen gebruikt ie de `authorization` header die gegenereerd was voor het vorige account.

Deze authorization string is niet te gebruiken over verschillende accounts dus zodra je het account id veranderd moet deze opnieuw gegenereerd worden.

**iOS app versie** (zoals die in de app store staat): v1.4.9
**iOS os versie**: 13.3
**iOS model**: iPhone Xs

**Comment by Gerben-T** [comment]
De authorization header die gegenereerd wordt kan gecheckt worden op https://admin.parley.nu/account/0W4qcE5aXoKq9OzvHxj2/settings/authorization.

Onder _Validate authorization header_ vul je dan de string in en druk je op "Validate".
Vervolgens probeert de api deze string te decrypten a.d.h.v. de informatie van het account waar je in zit.

De authorization string die ik kreeg toen ik naar account X wilde gaan heb ik niet kunnen decrypten in account X maar wel in het Parley Demo account, dus vandaar dat ik vermoed dat de authorization header niet opnieuw gegenereerd wordt als je switched van accounts in de demo app

**Comment by Gerben-T** [comment]
Zoals besproken in de Skype conversatie;

Deze situatie kwam voor door een backend issue van de Parley API, dus we kunnen er van uit gaan dat dit niet standaard voor komt.

We willen wel graag dat de error's die teruggegeven worden vanuit de API getoond worden in de app, dus dat wordt de oplossing voor dit issue.

De `notifications` uit het response object parsen en tonen als error/warning.

Parley zal een lijst aanleveren met error mapping in EN/NL, maar jullie kunnen als fase 1 alvast de error text uit het response object tonen.

Klinkt dat goed? @alexkok

**Comment by alexkok** [comment]
Yep! De Parley library parsed het `notifications` object uit het error response op dit moment niet, waardoor de gebruiker geen indicatie heeft wat er precies fout gaat. Het is wenselijk de melding vanuit de API te tonen aan de gebruiker.

Om dit op te lossen zal de Parley library het `notifications` object uit het error response moeten verwerken en dit tonen naar de gebruiker (in de demo app).

**Comment by alexkok** [comment]
Released in 3.9.1 🚀
