### ISSUE TITLE
Image detail not always loading

### ISSUE THREAD

**Issue by nlamah** [parley-messaging/ios-library#114]
**Describe the bug**
When pressing an image from the chat a modal screen opens and the full image can be viewed and zoomed. For some reason the image is not always loading without showing a loader or error.

**To Reproduce**
NB: this is not 100% reprodocible, but 
* Send an image in the chatView
* Start the app again (this helps to make the chance to reproduce a bit bigger)
* Select the image and wait until the detail screen has opened
* Actual result: Sometimes there is no image visible
* Expected result: There should be a loader visible when the image is being loaded, when the image can't be loaded an error should be shown

**Expected behaviour**
There should be a loader visible when the image is being loaded, when the image can't be loaded an error should be shown.

**Screenshots**

https://github.com/parley-messaging/ios-library/assets/2762698/7279f8a9-471f-4516-8166-b7d742e44b0a

**Comment by nlamah** [comment]
https://github.com/parley-messaging/ios-library/assets/2762698/7279f8a9-471f-4516-8166-b7d742e44b0a

**Comment by nlamah** [comment]
With the debugger I was able to reproduce that it is caused by the widthScale and heightScale, being zero. The image was loaded correctly.
![Screenshot 2024-05-30 at 13 54 52](https://github.com/parley-messaging/ios-library/assets/2762698/11539aa8-7b25-43a3-a27c-71b09dc4073c)

**Comment by alexkok** [comment]
Fixed and released in [4.1.1](https://github.com/parley-messaging/ios-library/releases/tag/4.1.1) 🚀
