### ISSUE TITLE
Gradients are randomly applied to loading image views

### ISSUE THREAD

**Issue by nlamah** [parley-messaging/ios-library#119]
**Describe the Bug**
When multiple images are loading and the view is scrolled, some loading image views get the gradient below the time and some won't

**To Reproduce**

- Open the chat
- Add some images and messages
- In code make sure the loaded image is not displayed (comment out https://github.com/parley-messaging/ios-library/blob/master/Sources/Parley/Views/ParleyMessageView/ParleyMessageView.swift#L367)
- Build the app again
- Scroll through the chats

**Expected behaviour**
The behaviour should be consistent, if a loading image view does not have the gradient, then it should not suddenly appear. Always showing the gradient could also be correct.

**Screenshots**

https://github.com/parley-messaging/ios-library/assets/2762698/6499b275-5d96-461d-b57e-4dc2f7bda849

**Comment by alexkok** [comment]
Fixed and released in [4.1.1](https://github.com/parley-messaging/ios-library/releases/tag/4.1.1) 🚀
