### ISSUE TITLE
Feed keeps loading at the top when AlwaysPolling is enabled

### ISSUE THREAD

**Issue by nlamah** [parley-messaging/ios-library#126]
**Describe the Bug**
When Parley is set to alwaysPolling and the the feed is scrolled to the top, when the first message is shown, most of the time the loader is visible instead of the info message.

**To Reproduce**

- In the example app set 'Parley.setAlwaysPolling(true)'.
- Add enough messages so that not all messages are loaded from cache
- Close the chat window
- Open the chat window
- Scroll to the first message of the feed
- Actual behaviour: Most of the time there is a loader at the top of the list, when the info message appears, the loader message appears short after that

**Expected behaviour**
When the first message is shown, and nothing the be loaded anymore, the loader should not appear, but always the info message.

**Screenshots**

https://github.com/parley-messaging/ios-library/assets/2762698/e7911689-8613-4bf1-b26a-8638e91c4cc2

**Comment by alexkok** [comment]
Turns out polling had some unintended side effects due to some other changes, under which this side effect as well. 

Fixed in [4.1.3](https://github.com/parley-messaging/ios-library/releases/tag/4.1.3) 🚀
