### ISSUE TITLE
Some special characters are formatted incorrectly

### ISSUE THREAD

**Issue by nlamah** [parley-messaging/ios-library#138]
**Describe the Bug**
Messages from the agent that contain one the following characters `&"'` are not formatted correctly. 

**To Reproduce**
* From the backend send a message that contains an apostrophe character.
* Open the iOS app
* Actual Result: The apostrophe character is shown as `&apos;`
**Expected behaviour**
Apostrophe is shown as `'`

**Screenshots**
![Screenshot 2024-06-17 at 12 56 29](https://github.com/parley-messaging/ios-library/assets/2762698/0a9d9478-3c60-4303-a91c-473300a57f67)

**Comment by alexkok** [comment]
Thanks for reporting, however, we don't see this happening. Tested with chatting via the dashboard and tested with using the serviceApi v2.1.

How are you sending the data from the backend exactly? Make sure it isn't encoding the characters there for example, we send this to the serviceApi and it shows as expected:

```
POST https://api.parley.nu/serviceApi/v2.1/users/<id>/messages
Authorization: ...
Content-Type: application/json

{
  "message": "Do you want more information? & ' \""
}
```

**Comment by Gerben-T** [comment]
This was an issue in the Parley Dashboard an has been resolved already.
I suggest we close this issue.
