### ISSUE TITLE
Setting fileActionFont does not get applied correctly

### ISSUE THREAD

**Issue by Nienke0905** [parley-messaging/ios-library#159]
Describe the Bug
When setting a different `fileActionFont` on `ParleyMessageViewAppearance` the new font does not get applied until the cell is laid out again.

Steps To Reproduce
- Set ` userMessage.fileActionFont` to a different font/size/weight in the sample app
- Run the sample app and send a document in the chat
- See the wrong font on the `OPEN` button being applied
- Click `Done`
- Navigate back to chat
- See the right font being applied

Expected behaviour
The `userMessage.fileActionFont` set in the project being applied immediately.

https://github.com/user-attachments/assets/68b6586c-422d-4561-955a-27d578c6ed84
https://github.com/user-attachments/assets/4539f742-1f3d-4850-8ffe-1e1577aca8ed

**Comment by alexkok** [comment]
Fixed & released in [4.2.2](https://github.com/parley-messaging/ios-library/releases/tag/4.2.2) 🚀
