### ISSUE TITLE
ChatViewController being dismissed and file uploaded 2x on sending file

### ISSUE THREAD

**Issue by Nienke0905** [parley-messaging/ios-library#164]
**Describe the bug:**
When sending a Document the ChatViewController gets dismissed. When navigating back to the chat, the file uploaded is displayed 2x.

**To Reproduce:**
1. Open Example app
2. Tap on "Start Chat"
3. Tap on the "**+**" button and select "Document"
4. Select a file to upload
5. The ViewController gets dismissed
6. Tap again on "Start Chat"
7. Two files instead of one are displayed

**Expected behaviour:**
The ChatViewController is not being dismissed and the file is only uploaded 1x.

**Video:**
https://github.com/user-attachments/assets/c10e090e-6b88-4f3a-82fa-0c2e886dd1da

**Comment by alexkok** [comment]
Thanks for reporting @Nienke0905 

I don't see this happening here, which iOS version and device are you using?

**Comment by alexkok** [comment]
We also don't see the chat dismissing after selecting a document 🤔

**Comment by Nienke0905** [comment]
Hi Alex, it seems to only be consistently reproducible on my MacBook specifically with certain simulators (regardless of iOS version), such as the iPhone 15 (iOS 17.5, 17.2), iPhone SE (3rd gen). But works as intended on other devices such as the iPhone 15 Pro. I've asked others to test it out, and they also do not see the problem. I'll close the issue.
