### ISSUE TITLE
Images flicker

### ISSUE THREAD

**Issue by Nienke0905** [parley-messaging/ios-library#166]
**Describe the bug:**
When images have been uploaded and the iOS device is moved backwards and forwards, the images flicker when the device is not locked in Portrait mode.

**To Reproduce:**
1. Swipe down from the top right-hand corner of your screen to open Control Centre
2. Check Portrait Orientation Lock button to make sure that it's off (allow Landscape)
3. Open Example app
4. Tap on "Start Chat"
5. Upload or take photos
6. Move device backwards and forwards (not going into landscape)

**Video:**
This has been reproduced on iPhone 8 (iOS 16), 11 (iOS 18) and 15 (iOS 17.7) by several people.

https://github.com/user-attachments/assets/f6e5f667-ca64-4245-aa29-9bed06d64f66
https://github.com/user-attachments/assets/7af3ff2e-c477-4a52-94a7-7d7c36e9f6b2

**Comment by alexkok** [comment]
Thanks for reporting!

Fixed & released in [4.2.3](https://github.com/parley-messaging/ios-library/releases/tag/4.2.3) 🚀
