### ISSUE TITLE
Project status? Current Example project does not seem to work.

### ISSUE THREAD

**Issue by martijnhoutman** [parley-messaging/ios-library#2]
Hi!

I am working on an integration of the Parley tool into a native app, and was looking for existing libraries. The documentation for the library mentioned on Parley's website (https://developers.parley.nu/docs/getting-started-1 ) is a bit lacking. I ran into this library, which seems to have more up-to-date, albeit being updated last 12 months ago.

Running the current Example project does give me a working interface, but the connection it tries to make seems to fail:

```
"Parley.reachable: true"
"Parley.configure(_, _, _)"
"Parley.configure(_, _)"
"ParleyRemote.execute:: post https://api.parley.nu/clientApi/v1.2/devices [\"type\": 2, \"userAdditionalInformation\": [\"name\": \"John Doe\", \"email\": \"j.doe@parley.nu\", \"address\": \"Randstad 21 30, 1314, Nederland\"], \"pushType\": 6, \"version\": \"3.0.0\"]"
"ParleyViewDelegate.didChangeState:: failed"
```

Initially I thought this was due to old certificate pinning hashes, but that does not seem to be the problem. I have a working value for `kUserDefaultIdentificationCodeDefault`, which we currently use on the website.

I was wondering if this project is still supported?

Kinds regards,
Martijn Houtman.

**Comment by sjongejan** [comment]
Hi Martijn,

Sorry for the late response. Yes, this library is still fully supported! 

Thanks for the detailed issue description, the public keys were indeed expired. 
Which public keys did you use in project? We have updated the example project with the new public keys and it works now.

Can you pull these changes and try it again? Let me know if that resolves the issue.

Kinds regards,
Stefan Jongejan

**Comment by martijnhoutman** [comment]
Hi Stefan,

Good to hear! And no worries, your response was very timely 👍 The demo seems to work now, thank you so much.

When I use my own provided roomId / kUserDefaultIdentificationCodeDefault I do still get the failed connection. Perhaps this has to do with permissions of the account I am working with, I suppose contacting Parley support might help with this. I will update on my progress.

Thanks for your help so far!

Regards,
Martijn.

**Comment by martijnhoutman** [comment]
Hi Stefan,

It was indeed something at my end, I had an invalid Authorization, as described here: https://developers.parley.nu/docs/authorization-header

I just had a short but successful conversation on our account, so all is good. 

I will now implement this further into our app. Thanks for your help so far! :) 

Regards,
Martijn.

**Comment by sjongejan** [comment]
Hi Martijn,

Thanks for the follow up, good to hear that it works now!

Feel free to create a new issue in case you encounter issues while implementing the library in your app.

Kind regards,
Stefan
