### ISSUE TITLE
Support Codable

### ISSUE THREAD

**Issue by igashev** [parley-messaging/ios-library#21]
Hello, 

Do you have any plans on supporting `Codable` and dropping `ObjectMapper`? This would highly increase the quality of you product and decrease the code that you would need to take care of.

**Comment by alexkok** [comment]
Hi @igashev , yes we would like to migrate to `Codable` in the future. Although there is no direct estimate when currently. Do you need this specifically for something?

(Or in the meantime, feel free to create a PR for this.)

**Comment by mat1th** [comment]
I've created a pr to remove the `ObjectMapper` dependecy and use `Codable` instead. You can find it [here](https://github.com/parley-messaging/ios-library/pull/53)

**Comment by mat1th** [comment]
This issue is resolved in #53. So this issue can be closed;

**Comment by alexkok** [comment]
Thanks for your contributions @mat1th! 
We have now moved away from ObjectMapper and use structs+codables instead.

Released in 3.9.0 🚀
