### ISSUE TITLE
Issues with carrousels

### ISSUE THREAD

**Issue by rubenaalders** [parley-messaging/ios-library#26]
It's more of a broad issue report. This issue has also been reported to Parley directly, but they suggested to post it here as you guys are subcontractors. Since web introduced the functionality for carrousels as well we tried putting it live as Wehkamp, but noticed a few issues. They apply to both the Android & iOS SDK so if this can be shared internally that would be awesome. 

1. messages only visible after reopening messaging window
2. carroussels make app crash
3. carroussels and quick reply don’t work

**Comment by alexkok** [comment]
Thanks @rubenaalders , we'll check the functionality with carousels on both Android & iOS and come back to it.

> 1. messages only visible after reopening messaging window

Do you mean **all messages** here, or only the newer types such as the carousel/quickreplies? 
On iOS this could also be related to debug builds in combination with push (iOS also supports polling instead)
Just to be sure: is this one also the case for Android?

**Comment by MennoRozema** [comment]
Hi @rubenaalders, @alexkok en @Gerben-T 

Als ik dit kaartje zo bekijk, heb ik het gevoel dat iedereen een beetje op elkaar wacht. Terwijl we allemaal hetzelfde doel hebben; Zo snel mogelijk een werkbare situatie creëren voor Wehkamp, met betrekking tot de Buttons, carrousels etc.

Is het een idee om even een call te plannen met ons vieren, om te bespreken hoe we vanaf hier verdergaan?

Groeten,
Menno

**Comment by alexkok** [comment]
Hi @rubenaalders,

Thanks for your response! Alright, let us know the findings about point 1 when that is more clear.

We'll check the functionality concerning points 2 and 3. Thanks for the example and stacktrace 👍

**Comment by alexkok** [comment]
We've resolved the crashes that happened when using carousels and quick replies (point 2 and 3).

@rubenaalders please check out version 3.5.1, let us know if this solves the issues you were facing.

Sidenote: We didn't see these issues inside the Android library, feel free to open an issue in the Android repo if needed.

Also feel free to reopen, or open a new issue, when facing any issues.

**Comment by alexkok** [comment]
Fixed in #27, released in version 3.5.1 🚀
