### ISSUE TITLE
SDK contains multiple memory leaks;

### ISSUE THREAD

**Issue by mat1th** [parley-messaging/ios-library#57]
**Describe the bug**
I'm trying the demo app that is included in the project. When starting and stopping the chat the shown `ParleyView` and other view objects do stay in memory. This is caused multiple memory leaks.

**To Reproduce**
1. Start the example app.
2. Open a new chat.
3. Stop the chat.
4. Open a new chat.
3. Stop the chat.
4. Open a new chat.
5. Stop the chat.
6. Open "Debug memory graph" in Xcode.
7. See multiple instances of the`ParleyView` object in memory.

**Expected behaviour**
I do expect that the SDK does deinit the view when it is dismissed.

**Screenshots**
<img width="231" alt="memory" src="https://github.com/parley-messaging/ios-library/assets/6486389/0b6cb780-d04f-4356-92eb-d91d6b51290c">

**Comment by alexkok** [comment]
Thanks for reporting! We'll look into it

**Comment by mat1th** [comment]
Thank you, I've already fixed some in https://github.com/parley-messaging/ios-library/pull/58, but there are more.

**Comment by mat1th** [comment]
Great thank you for fixing @alexkok!

**Comment by alexkok** [comment]
Released in 3.9.1 🚀
