### ISSUE TITLE
Make it possible to hide the pushDisabledNotificationView

### ISSUE THREAD

**Issue by mat1th** [parley-messaging/ios-library#73]
**Describe the feature**
We would like to hide the message in the chat view that indicates the push notification authorization status. Right now this message is shown/hidden based on the phone settings but we would like to be more in control over when we inform the user about push. Right now we can't change anything about this logic in the chat view, so we need to change the SDK.

**Possible solution**
A rather quick solution could be to make `@IBOutlet weak var pushDisabledNotificationView: ParleyNotificationView!` [public](https://github.com/parley-messaging/ios-library/blob/master/Sources/Parley/Views/ParleyView.swift#L22) so we can hide it.

**Comment by mat1th** [comment]
Agree that making it public is not a ideal solution. Sounds like a good plan to make it part of the `Appearance` structure. Thank you for looking into it!
_Yes we will inform the user our self that push is disabled._

**Comment by alexkok** [comment]
Fixed in #74 , will be released with 4.0.0 🚀 

(use `appearance.pushDisabledNotification.show = false` to disable showing this view)

**Comment by mat1th** [comment]
Hi @alexkok,
Great! Thank you for fixing it so fast!

**Comment by alexkok** [comment]
No problem!

Released in 4.0.0 🚀
