### ISSUE TITLE
Feat: Make it possible to style the ParleyView.activityIndicatorView

### ISSUE THREAD

**Issue by mat1th** [parley-messaging/ios-library#79]
**Describe the feature**
I would like to style the [activityIndicator](https://github.com/parley-messaging/ios-library/blob/master/Sources/Parley/Views/ParleyView.swift#L52) in the `ParleyView`. This is not possible for now. Only the loader in the `LoadingTableViewCell` has an option to change the [appearance](https://github.com/parley-messaging/ios-library/blob/master/Sources/Parley/Views/TableViewCells/LoadingTableViewCell/LoadingTableViewCellAppearance.swift).

**Screenshot**
![Screenshot 2024-04-08 at 11 23 09](https://github.com/parley-messaging/ios-library/assets/6486389/592f609e-911c-42bb-85e8-7a04dad6fdeb)

**Possible solution**
A possible way of solving this issue is adding a new `Appearance` option to the `ParleyViewAppearance` class and apply this `Appearance` to the `activityIndicator` in the `ParleyView`.

**Comment by alexkok** [comment]
Thanks for reporting! 

You are right, there's no appearance option for this loader. 
Lets add it to the `ParleyViewAppearance` as `loaderTintColor` as well and apply that.
