### ISSUE TITLE
Only ask for photoRoll permission when the user wants to Select Photo

### ISSUE THREAD

**Issue by nlamah** [parley-messaging/ios-library#86]
When the user wants to send an image they select the camera icon left to the inputTextField.
In the current implementation first the permission with the title '"Parley" Would like to Access Your Photos' appears. After the user makes a decision the bottom sheet with the options to 'Select Photo' and 'Take Photo' appear.
The expected behaviour would be that the photo permission popup appears after the 'Select Photo' option is selected.

https://github.com/parley-messaging/ios-library/assets/2762698/ec58b105-9fa4-4256-be13-9465415ad1b2

**Comment by alexkok** [comment]
Improved and released in [4.1.1](https://github.com/parley-messaging/ios-library/releases/tag/4.1.1) 🚀
