### ISSUE TITLE
Use PHPickerViewController for selecting an image

### ISSUE THREAD

**Issue by nlamah** [parley-messaging/ios-library#87]
This issue is to point out the benefit of using `PHPickerViewController` for selecting images.
No permission of the user is needed and it can be used to select pdfs. It can be used for iOS 14 and up.

https://jokerpt.medium.com/using-phpickerviewcontroller-in-ios-apps-f7ddd68214ee

**Comment by alexkok** [comment]
Improved and released in [4.1.1](https://github.com/parley-messaging/ios-library/releases/tag/4.1.1) 🚀
