### ISSUE TITLE
Lazy loading of messages does sometimes not work when OfflineMessaging is disabled.

### ISSUE THREAD

**Issue by mat1th** [parley-messaging/ios-library#91]
**Describe the bug**
When you disable OfflineMessaging in the example app and you scroll upwards. It will stop lazy loading the messages on some moment. 

**To Reproduce**
1. Set `kOfflineMessagingEnabled` to false in the `IdentifierViewController`.
1. Start the example app.
3. Open a new chat with a lot of messages.
5. Scroll upwards to load the new messages.
6. The lazy load loader will stay on top (see screenshot) and the oldest messages are not loaded.

**Expected behaviour**
I do expect that the SDK lazy loads new messages when scrolling. 

**Screenshots**
![loader](https://github.com/parley-messaging/ios-library/assets/6486389/cf949b37-c781-4564-8413-fcf45bb3fcda)

**Comment by alexkok** [comment]
Thanks for reporting! Fixed the issue in [4.1.2](https://github.com/parley-messaging/ios-library/releases/tag/4.1.2) 🚀

**Comment by nlamah** [comment]
I found another case where this issue is happening. See this new issue: https://github.com/parley-messaging/ios-library/issues/126
