### ISSUE TITLE
Add support for new localizations.

### ISSUE THREAD

**Issue by mat1th** [parley-messaging/ios-library#95]
**Describe the feature**
The SDK only supports 2 localizations for now the [nl](https://github.com/parley-messaging/ios-library/blob/master/Sources/Parley/nl.lproj/Localizable.strings) and [en](https://github.com/parley-messaging/ios-library/blob/master/Sources/Parley/en.lproj/Localizable.strings) localization. We would like to support more languages in our app. For now this is only possible with manually adding translations because it is always searching in the[ SDK bundle](https://github.com/parley-messaging/ios-library/blob/master/Sources/Parley/Extensions/StringExtension.swift#L36). 

**Screenshot**
NA

**Possible solution**
A possible solution would be to add the localization strings to the `Appearance` objects. 
There are only two kinds of places where this is not possible. 
- Views without an `Appearance` object (`MessageImageViewController`). To solve this a new `Appearance` object should be created.
- Non UI usage: Places where translations are used are `Parley`, `Message+Accessibility` and `MediaUploadNotificationErrorKind`. To solve this, the logic needs to be extracted and moved to the UI.

Is this a okay solution, or do you want separate objects for the translations?

**Comment by alexkok** [comment]
Hi @mat1th , thanks for reporting. 

All keys are prefixed by `parley_` already and we would allow overriding these when wanted (just like Android used to do).
However, as you describe, it currently only searches in the module bundle, making it impossible to override.

While the suggested solution could work, we are thinking of a different approach:
- Adjusting the code in [StringExtension](https://github.com/parley-messaging/ios-library/blob/master/Sources/Parley/Extensions/StringExtension.swift#L36)
- Where we adjust it such that it first checks if the needed localization is in the main/other bundle, and if not, take it from the sdk bundle as fallback.
- Note that `NSLocalizedString` always returns the key if it cannot be found. So to do this we could check if we get the key returned as result, and if so, take string from the sdk bundle instead.
- Benefit of this is that it saves much code, and we don't need to introduce additional properties/classes to support this. Also allows to override any string used by Parley.
- About stability, in case new strings are introduced or renamed (this doesn't happen much) we need to mention these in the [CHANGELOG.md](https://github.com/parley-messaging/ios-library/blob/master/CHANGELOG.md)

How does this sound to you?

**Comment by mat1th** [comment]
We do also have the option in our app to overwrite the system locale. So for example a user does has his system language to `en` while the app will use `nl` while the app does also support `en`.

With you supposed solution this will not work for us.

**Comment by mat1th** [comment]
Hi @alexkok,

I've made a implementation on https://github.com/parley-messaging/ios-library/compare/master...mat1th:feature/implement-custom-localization-option?expand=1 Is this the way you would like to see it? If so I can open a PR.
